# Generated by Django 3.2 on 2024-11-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenGymApp', '0005_alter_plan_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='duracion_meses',
            new_name='duracion_dias',
        ),
    ]
